# Generated by Django 4.2.6 on 2023-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("price", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("brand", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=50)),
                ("rating", models.IntegerField()),
            ],
            options={
                "db_table": "product_table",
            },
        ),
    ]
